import '@storybook/addon-links/register';
import '@storybook/addon-viewport/register';
import '@storybook/addon-backgrounds/register';
import '@storybook/addon-knobs/register';
import '@storybook/addon-storysource/register';
// import '@rakuten-rex/storybook-inspecthtml/register';
// import '../src/storybook-inspect-html/register';
import '../npm/register';
import '@rakuten-rex/storybook-inspectjsx/register';
import '@storybook/addon-actions/register';
import '@storybook/addon-a11y/register';
